In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from sklearn.datasets import make_classification

In [46]:
#create the dataset
X,y = make_classification(n_samples=1000, n_features=10, n_classes=2, random_state=30)

In [47]:
X

array([[-2.26689933,  1.49959359,  0.75965452, ..., -0.74250649,
         1.0170277 , -1.45644926],
       [-1.28997309,  0.8331157 ,  0.41769573, ...,  0.2121813 ,
        -0.36359052, -0.83983932],
       [ 0.22216965,  1.38907741,  1.03319923, ...,  0.15190194,
         0.72825596,  0.98205686],
       ...,
       [ 0.20849575,  1.14820907,  0.85756747, ...,  1.11610857,
         0.00848992,  0.83671534],
       [-2.38812834, -0.34532195, -0.58792652, ..., -0.78802051,
        -0.22142448, -2.58624305],
       [ 0.04440334,  0.73896088,  0.53916948, ..., -0.75412292,
         0.30822932,  0.44835661]])

In [48]:
y

array([1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 1])

In [49]:
pd.DataFrame(X)

,0,1,2,3,4,5,6,7,8,9
0,-2.266899,1.499594,0.759655,0.122765,-2.315735,-0.019930,-0.132149,-0.742506,1.017028,-1.456449
1,-1.289973,0.833116,0.417696,-0.284231,-1.066789,-0.073931,-0.026814,0.212181,-0.363591,-0.839839
2,0.222170,1.389077,1.033199,0.598068,0.384157,-0.217773,1.403139,0.151902,0.728256,0.982057
3,-1.266009,1.337652,0.784920,0.733756,-1.161272,-0.172708,0.211214,-0.424339,1.685622,-0.540096
4,-1.027363,0.667609,0.335617,0.250314,1.582328,0.121074,0.034026,0.948339,0.895196,-0.666628
...,...,...,...,...,...,...,...,...,...,...
995,0.027508,0.568849,0.414103,0.662608,-0.284284,-0.110962,-0.361262,0.493847,-0.551548,0.338443
996,2.143101,0.214668,0.458938,-1.087562,0.382458,-0.970834,0.288722,-0.843561,0.507008,2.268858
997,0.208496,1.148209,0.857567,-0.314116,-1.741188,0.967866,-0.632848,1.116109,0.008490,0.836715
998,-2.388128,-0.345322,-0.587927,-0.181420,0.206793,0.540870,0.431581,-0.788021,-0.221424,-2.586243
999,0.044403,0.738961,0.539169,-0.632168,-0.212384,-1.446757,-1.275500,-0.754123,0.308229,0.448357

In [50]:
pd.DataFrame(y)

     0
0    1
1    1
2    1
3    1
4    1
..  ..
995  1
996  0
997  1
998  0
999  1

[1000 rows x 1 columns]

In [51]:


from sklearn.model_selection import train_test_split
train_X, test_X, train_y, test_y = train_test_split(X,y,test_size=0.30,random_state=42)

In [52]:

# Model training
from sklearn.linear_model import LogisticRegression
logistic_model = LogisticRegression()

In [53]:
logistic_model.fit(train_X, train_y)

LogisticRegression()

In [54]:
y_pred_train = logistic_model.predict(train_X)
y_pred_test = logistic_model.predict(test_X)
print(y_pred_train)
print(y_pred_test)

[0 0 0 1 1 1 1 0 0 0 0 0 1 1 0 0 1 0 1 0 1 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 1
 1 1 0 0 0 0 1 0 1 1 0 0 0 1 0 1 0 0 0 0 0 1 1 1 1 1 1 0 0 0 1 1 1 0 0 1 0
 0 0 0 0 1 1 0 0 0 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 0 1 0 0 0 0 0 0 0 0 1 1 1
 1 0 1 0 0 1 0 1 1 0 1 1 1 1 0 0 1 0 0 1 1 1 1 1 0 0 0 1 1 1 1 1 0 1 1 1 1
 1 1 1 1 1 0 1 0 1 0 0 1 0 0 0 1 0 0 1 1 0 1 1 1 0 1 1 0 0 0 0 0 1 1 1 1 0
 1 0 0 1 1 1 0 1 0 1 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 1 1 1 1 1 0 1 0 0 0 0 0
 1 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 1 0 1 1 0 1 0 1 1 1 1 1 0 1 1 0 0 0 0 0 0
 0 1 1 0 0 0 1 1 0 0 1 1 0 1 1 1 1 0 1 0 1 1 0 1 0 0 1 0 0 1 0 0 0 1 0 1 1
 0 1 0 0 0 1 0 0 0 1 0 1 1 1 0 0 1 1 0 0 1 1 0 1 1 0 0 1 1 0 1 1 0 1 1 0 1
 0 0 1 0 1 0 0 0 0 1 0 1 1 0 1 1 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 1 0 0 0 0 1
 0 1 0 1 0 0 1 0 1 0 0 1 0 0 1 0 0 1 1 0 0 1 1 1 0 0 1 0 0 1 0 0 0 0 0 1 1
 0 1 0 0 0 0 1 0 1 1 0 1 0 1 1 1 1 1 0 1 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 1 0
 1 0 1 0 0 0 1 1 0 0 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 0 0 0 0 0 0 1 0 1 0 0 1
 0 0 1 0 1 0 1 1 1 0 0 1 1 0 0 0 0 1 1 0 1 0 0 1 0 0 1 1 0 1 1 0 0 1 0 0 1
 1 1 1 1 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 1 0 1 1 1 1 1 0 0 1 1 0 1 0 1 0 1 1
 1 0 0 1 0 0 1 0 0 1 0 0 1 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 1 1 0 1 0 1
 1 0 1 0 0 0 0 1 0 0 0 1 1 1 1 1 1 0 0 0 1 1 1 1 0 0 0 1 0 1 0 0 0 0 1 1 0
 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 1 0 0 1 1 0 1 1 1 1 0 1 1 0 0 0 0 0
 1 1 0 0 1 1 1 0 1 1 1 1 0 0 1 0 0 1 0 0 0 1 1 0 1 0 1 0 0 1 1 1 1 0]
[1 0 1 0 1 1 1 0 0 0 0 1 0 0 1 1 1 1 0 1 1 1 0 1 0 0 0 0 1 0 1 0 1 0 1 1 0
 0 0 0 0 1 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 0 0 1 0 0 1 0 1 1 0 1 0 1 1 1 1 0
 0 0 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 1 1 0 1 0 0
 0 1 0 0 1 0 0 0 0 1 1 1 0 0 1 1 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 0 0 1 1 1
 0 0 0 0 1 1 1 0 0 0 0 1 0 0 0 1 1 0 1 0 1 1 0 0 0 1 1 0 0 0 0 1 1 0 0 0 1
 1 1 1 1 0 1 1 1 0 1 0 1 1 0 1 0 0 0 0 0 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 1
 1 0 1 1 1 0 0 1 0 1 0 0 0 1 0 0 0 1 1 1 1 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 1
 1 0 0 0 1 0 1 1 1 1 1 1 1 1 1 1 0 1 0 1 0 1 1 1 1 0 1 0 1 1 0 0 1 1 1 1 0
 0 0 0 0]

In [55]:

logistic_model.predict_proba(test_X)

array([[7.87673616e-03, 9.92123264e-01],
       [9.77814619e-01, 2.21853806e-02],
       [1.41276008e-01, 8.58723992e-01],
       [8.50994153e-01, 1.49005847e-01],
       [1.11519008e-02, 9.88848099e-01],
       [7.81658668e-03, 9.92183413e-01],
       [3.32432595e-02, 9.66756741e-01],
       [7.91055405e-01, 2.08944595e-01],
       [9.99755712e-01, 2.44287772e-04],
       [9.99671341e-01, 3.28659260e-04],
       [5.81332640e-01, 4.18667360e-01],
       [6.68378776e-03, 9.93316212e-01],
       [8.91972797e-01, 1.08027203e-01],
       [9.72651622e-01, 2.73483776e-02],
       [3.63419805e-03, 9.96365802e-01],
       [4.12135097e-03, 9.95878649e-01],
       [1.84531990e-03, 9.98154680e-01],
       [1.89629261e-04, 9.99810371e-01],
       [9.32240556e-01, 6.77594439e-02],
       [6.90920396e-03, 9.93090796e-01],
       [1.78664398e-02, 9.82133560e-01],
       [4.20969177e-01, 5.79030823e-01],
       [9.93271847e-01, 6.72815339e-03],
       [3.77016955e-01, 6.22983045e-01],
       [9.87014357e-01, 1.29856426e-02],
       [7.59388343e-01, 2.40611657e-01],
       [9.93767013e-01, 6.23298701e-03],
       [9.98932787e-01, 1.06721328e-03],
       [5.16679727e-03, 9.94833203e-01],
       [9.66376561e-01, 3.36234391e-02],
       [3.79466925e-04, 9.99620533e-01],
       [9.92350912e-01, 7.64908769e-03],
       [2.54092550e-02, 9.74590745e-01],
       [9.93185276e-01, 6.81472418e-03],
       [5.39939943e-03, 9.94600601e-01],
       [1.10244869e-02, 9.88975513e-01],
       [9.99125930e-01, 8.74069850e-04],
       [9.61341040e-01, 3.86589595e-02],
       [9.90690883e-01, 9.30911748e-03],
       [9.98805325e-01, 1.19467469e-03],
       [9.96770523e-01, 3.22947697e-03],
       [2.19240753e-01, 7.80759247e-01],
       [1.82766107e-01, 8.17233893e-01],
       [5.13590621e-03, 9.94864094e-01],
       [9.50090444e-01, 4.99095557e-02],
       [1.05656520e-02, 9.89434348e-01],
       [4.94049573e-05, 9.99950595e-01],
       [4.98768148e-04, 9.99501232e-01],
       [4.46027157e-04, 9.99553973e-01],
       [5.86540070e-03, 9.94134599e-01],
       [4.75387807e-02, 9.52461219e-01],
       [2.46308246e-01, 7.53691754e-01],
       [2.08996390e-02, 9.79100361e-01],
       [9.87630977e-01, 1.23690230e-02],
       [2.01157075e-05, 9.99979884e-01],
       [5.96139724e-03, 9.94038603e-01],
       [3.12929990e-02, 9.68707001e-01],
       [9.96451119e-01, 3.54888084e-03],
       [9.60406201e-01, 3.95937991e-02],
       [1.18771888e-03, 9.98812281e-01],
       [9.68949767e-01, 3.10502327e-02],
       [7.27635396e-01, 2.72364604e-01],
       [4.88616880e-02, 9.51138312e-01],
       [6.93631607e-01, 3.06368393e-01],
       [2.81618827e-02, 9.71838117e-01],
       [8.41426013e-03, 9.91585740e-01],
       [9.46747690e-01, 5.32523098e-02],
       [1.27449459e-02, 9.87255054e-01],
       [6.50056409e-01, 3.49943591e-01],
       [7.76720103e-03, 9.92232799e-01],
       [3.96774598e-02, 9.60322540e-01],
       [3.01541547e-02, 9.69845845e-01],
       [1.89070696e-03, 9.98109293e-01],
       [7.17739290e-01, 2.82260710e-01],
       [8.61238755e-01, 1.38761245e-01],
       [8.92374200e-01, 1.07625800e-01],
       [3.92216111e-03, 9.96077839e-01],
       [9.77202222e-01, 2.27977778e-02],
       [8.89143758e-01, 1.10856242e-01],
       [7.59153093e-02, 9.24084691e-01],
       [1.74618683e-02, 9.82538132e-01],
       [9.99934766e-01, 6.52342340e-05],
       [9.77368522e-01, 2.26314777e-02],
       [3.36201955e-01, 6.63798045e-01],
       [8.57325550e-02, 9.14267445e-01],
       [4.64227479e-02, 9.53577252e-01],
       [4.92889109e-01, 5.07110891e-01],
       [9.25579514e-01, 7.44204861e-02],
       [4.21862597e-01, 5.78137403e-01],
       [1.96146358e-02, 9.80385364e-01],
       [6.93464429e-01, 3.06535571e-01],
       [7.72270899e-01, 2.27729101e-01],
       [3.97443650e-03, 9.96025563e-01],
       [6.56204647e-02, 9.34379535e-01],
       [4.11993331e-01, 5.88006669e-01],
       [1.12688553e-01, 8.87311447e-01],
       [2.05567560e-01, 7.94432440e-01],
       [1.57148338e-02, 9.84285166e-01],
       [9.91639830e-01, 8.36016990e-03],
       [9.95573553e-01, 4.42644686e-03],
       [7.39538306e-01, 2.60461694e-01],
       [9.43629898e-01, 5.63701023e-02],
       [7.68041671e-01, 2.31958329e-01],
       [6.77422090e-01, 3.22577910e-01],
       [8.52069125e-01, 1.47930875e-01],
       [1.29945362e-02, 9.87005464e-01],
       [1.07576203e-02, 9.89242380e-01],
       [9.74978657e-01, 2.50213430e-02],
       [2.61787346e-03, 9.97382127e-01],
       [9.84931219e-01, 1.50687810e-02],
       [9.66148608e-01, 3.38513921e-02],
       [9.28879827e-01, 7.11201731e-02],
       [2.17766803e-01, 7.82233197e-01],
       [9.29362531e-01, 7.06374694e-02],
       [9.71976433e-01, 2.80235670e-02],
       [1.77834487e-02, 9.82216551e-01],
       [8.83257960e-01, 1.16742040e-01],
       [9.73339845e-01, 2.66601551e-02],
       [5.80910394e-01, 4.19089606e-01],
       [9.02174303e-01, 9.78256974e-02],
       [2.17631639e-03, 9.97823684e-01],
       [3.58621022e-03, 9.96413790e-01],
       [9.77350538e-05, 9.99902265e-01],
       [9.06978867e-01, 9.30211329e-02],
       [6.62306948e-01, 3.37693052e-01],
       [1.11375514e-01, 8.88624486e-01],
       [4.16829356e-03, 9.95831706e-01],
       [1.35984234e-01, 8.64015766e-01],
       [7.03327822e-01, 2.96672178e-01],
       [1.26636304e-03, 9.98733637e-01],
       [1.48859888e-01, 8.51140112e-01],
       [2.45288933e-02, 9.75471107e-01],
       [1.87639104e-04, 9.99812361e-01],
       [1.06193531e-01, 8.93806469e-01],
       [9.92957656e-01, 7.04234442e-03],
       [4.07344748e-03, 9.95926553e-01],
       [1.99644784e-05, 9.99980036e-01],
       [9.93804061e-01, 6.19593903e-03],
       [6.28182978e-04, 9.99371817e-01],
       [7.56309171e-03, 9.92436908e-01],
       [1.02713098e-02, 9.89728690e-01],
       [3.27636294e-03, 9.96723637e-01],
       [3.67142233e-01, 6.32857767e-01],
       [9.92703283e-01, 7.29671688e-03],
       [9.90545184e-01, 9.45481587e-03],
       [9.28258821e-02, 9.07174118e-01],
       [9.62181410e-02, 9.03781859e-01],
       [6.10186886e-02, 9.38981311e-01],
       [9.56228387e-01, 4.37716131e-02],
       [8.59592260e-01, 1.40407740e-01],
       [8.41377621e-01, 1.58622379e-01],
       [9.87542824e-01, 1.24571758e-02],
       [2.53988305e-01, 7.46011695e-01],
       [1.10663380e-02, 9.88933662e-01],
       [1.94229273e-03, 9.98057707e-01],
       [8.69975141e-01, 1.30024859e-01],
       [9.47147124e-01, 5.28528760e-02],
       [6.49652685e-01, 3.50347315e-01],
       [9.24092985e-01, 7.59070154e-02],
       [1.35977894e-02, 9.86402211e-01],
       [9.99072205e-01, 9.27795498e-04],
       [9.99755438e-01, 2.44561605e-04],
       [9.82567246e-01, 1.74327543e-02],
       [3.43168144e-03, 9.96568319e-01],
       [8.60066862e-03, 9.91399331e-01],
       [9.75904056e-01, 2.40959441e-02],
       [1.53321276e-02, 9.84667872e-01],
       [9.93891773e-01, 6.10822729e-03],
       [1.63217995e-02, 9.83678200e-01],
       [2.55888992e-01, 7.44111008e-01],
       [9.99163462e-01, 8.36538341e-04],
       [5.99966814e-01, 4.00033186e-01],
       [9.52357030e-01, 4.76429704e-02],
       [5.48522576e-02, 9.45147742e-01],
       [2.57246787e-01, 7.42753213e-01],
       [9.94737820e-01, 5.26217972e-03],
       [9.40394786e-01, 5.96052139e-02],
       [8.73858436e-01, 1.26141564e-01],
       [9.73340323e-01, 2.66596773e-02],
       [7.05782755e-03, 9.92942172e-01],
       [2.21812813e-02, 9.77818719e-01],
       [9.74053145e-01, 2.59468547e-02],
       [6.88108250e-01, 3.11891750e-01],
       [9.90015026e-01, 9.98497446e-03],
       [3.45932158e-07, 9.99999654e-01],
       [2.11086118e-02, 9.78891388e-01],
       [2.10676691e-02, 9.78932331e-01],
       [2.23623392e-03, 9.97763766e-01],
       [2.54898217e-02, 9.74510178e-01],
       [9.25515869e-01, 7.44841308e-02],
       [3.49455758e-04, 9.99650544e-01],
       [1.24870671e-02, 9.87512933e-01],
       [2.55138550e-02, 9.74486145e-01],
       [9.23996302e-01, 7.60036977e-02],
       [1.45613323e-02, 9.85438668e-01],
       [9.98666175e-01, 1.33382490e-03],
       [1.65225438e-02, 9.83477456e-01],
       [2.66477925e-02, 9.73352208e-01],
       [9.15305632e-01, 8.46943677e-02],
       [3.27151282e-02, 9.67284872e-01],
       [8.51744631e-01, 1.48255369e-01],
       [7.55547968e-01, 2.44452032e-01],
       [9.53797441e-01, 4.62025593e-02],
       [8.01491532e-01, 1.98508468e-01],
       [9.95310861e-01, 4.68913918e-03],
       [3.78255345e-04, 9.99621745e-01],
       [9.91561035e-01, 8.43896515e-03],
       [2.48025624e-01, 7.51974376e-01],
       [2.45766795e-03, 9.97542332e-01],
       [2.00504952e-01, 7.99495048e-01],
       [5.12230850e-01, 4.87769150e-01],
       [2.52871153e-02, 9.74712885e-01],
       [2.57692016e-02, 9.74230798e-01],
       [9.83765458e-01, 1.62345419e-02],
       [9.32264556e-01, 6.77354439e-02],
       [1.91226981e-01, 8.08773019e-01],
       [1.62762621e-03, 9.98372374e-01],
       [3.65242215e-03, 9.96347578e-01],
       [1.19221489e-01, 8.80778511e-01],
       [1.92921704e-01, 8.07078296e-01],
       [1.80194899e-03, 9.98198051e-01],
       [5.62764206e-04, 9.99437236e-01],
       [1.86325656e-02, 9.81367434e-01],
       [9.97117882e-01, 2.88211801e-03],
       [1.56795448e-01, 8.43204552e-01],
       [5.70889115e-03, 9.94291109e-01],
       [2.37476442e-03, 9.97625236e-01],
       [9.96182442e-01, 3.81755753e-03],
       [8.96674660e-01, 1.03325340e-01],
       [6.00284946e-03, 9.93997151e-01],
       [7.49546686e-01, 2.50453314e-01],
       [2.29378785e-02, 9.77062121e-01],
       [8.02306763e-01, 1.97693237e-01],
       [9.76375920e-01, 2.36240795e-02],
       [9.94373646e-01, 5.62635380e-03],
       [1.09021534e-01, 8.90978466e-01],
       [5.13220670e-01, 4.86779330e-01],
       [7.58455604e-01, 2.41544396e-01],
       [7.54600473e-01, 2.45399527e-01],
       [8.82761718e-04, 9.99117238e-01],
       [4.00507768e-03, 9.95994922e-01],
       [5.79652284e-03, 9.94203477e-01],
       [4.70142756e-03, 9.95298572e-01],
       [9.60025251e-01, 3.99747489e-02],
       [8.09847832e-01, 1.90152168e-01],
       [9.95843587e-01, 4.15641336e-03],
       [9.95812350e-01, 4.18764967e-03],
       [5.88104558e-01, 4.11895442e-01],
       [6.56546064e-04, 9.99343454e-01],
       [9.19277930e-01, 8.07220695e-02],
       [1.73006798e-02, 9.82699320e-01],
       [9.75133045e-01, 2.48669548e-02],
       [1.95844987e-02, 9.80415501e-01],
       [9.99065448e-01, 9.34551669e-04],
       [9.01416160e-01, 9.85838403e-02],
       [7.70900246e-01, 2.29099754e-01],
       [9.78039771e-01, 2.19602292e-02],
       [9.83344718e-01, 1.66552820e-02],
       [2.70748002e-02, 9.72925200e-01],
       [1.16777120e-02, 9.88322288e-01],
       [8.39844683e-01, 1.60155317e-01],
       [8.94050433e-01, 1.05949567e-01],
       [9.94244633e-01, 5.75536721e-03],
       [2.63567149e-01, 7.36432851e-01],
       [9.85455784e-01, 1.45442158e-02],
       [9.38130124e-02, 9.06186988e-01],
       [7.66243688e-02, 9.23375631e-01],
       [2.08990057e-01, 7.91009943e-01],
       [1.69944686e-01, 8.30055314e-01],
       [2.75064569e-02, 9.72493543e-01],
       [9.84039777e-03, 9.90159602e-01],
       [3.57774299e-01, 6.42225701e-01],
       [9.10202086e-03, 9.90897979e-01],
       [1.14006593e-03, 9.98859934e-01],
       [2.59753235e-02, 9.74024676e-01],
       [9.98804591e-01, 1.19540887e-03],
       [2.58046326e-01, 7.41953674e-01],
       [9.39443750e-01, 6.05562502e-02],
       [1.51083043e-01, 8.48916957e-01],
       [9.93523059e-01, 6.47694074e-03],
       [2.38292019e-03, 9.97617080e-01],
       [3.81602782e-02, 9.61839722e-01],
       [4.51245618e-03, 9.95487544e-01],
       [8.51161943e-02, 9.14883806e-01],
       [8.51645260e-01, 1.48354740e-01],
       [2.12637263e-03, 9.97873627e-01],
       [9.94937834e-01, 5.06216632e-03],
       [2.09403007e-03, 9.97905970e-01],
       [5.41855085e-03, 9.94581449e-01],
       [9.74461207e-01, 2.55387925e-02],
       [6.64679586e-01, 3.35320414e-01],
       [4.58874273e-02, 9.54112573e-01],
       [2.93192162e-02, 9.70680784e-01],
       [4.52339364e-03, 9.95476606e-01],
       [3.37481277e-02, 9.66251872e-01],
       [9.53267214e-01, 4.67327862e-02],
       [8.26113611e-01, 1.73886389e-01],
       [9.86421546e-01, 1.35784536e-02],
       [9.77717031e-01, 2.22829695e-02],
       [9.08858498e-01, 9.11415016e-02]])

In [56]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print(accuracy_score(train_y, y_pred_train))
print(accuracy_score(test_y, y_pred_test))

0.9257142857142857
0.9666666666666667

In [57]:
print(confusion_matrix(train_y, y_pred_train))
print('---------------------------------------')
print(confusion_matrix(test_y, y_pred_test))

[[342  19]
 [ 33 306]]
---------------------------------------
[[134   5]
 [  5 156]]

In [58]:
print(classification_report(train_y, y_pred_train))
print('---------------------------------------')
print(classification_report(test_y, y_pred_test))

              precision    recall  f1-score   support

           0       0.91      0.95      0.93       361
           1       0.94      0.90      0.92       339

    accuracy                           0.93       700
   macro avg       0.93      0.93      0.93       700
weighted avg       0.93      0.93      0.93       700

---------------------------------------
              precision    recall  f1-score   support

           0       0.96      0.96      0.96       139
           1       0.97      0.97      0.97       161

    accuracy                           0.97       300
   macro avg       0.97      0.97      0.97       300
weighted avg       0.97      0.97      0.97       300

# Hyperparameter Tuning and Cross Validation

In [59]:

model = LogisticRegression()
penalty = ['l1', 'l2', 'elasticnet']
c_value= [100, 10 ,1.0, 0.1, 0.01]
solver = ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']

In [60]:
params = dict(penalty = penalty, C = c_value, solver = solver)

In [61]:
from sklearn.model_selection import StratifiedKFold
cv = StratifiedKFold()

In [62]:
## Grid Search CV
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(estimator=model, param_grid=params, scoring='accuracy', cv=cv, n_jobs=-1)

In [63]:
grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [64]:
grid.fit(train_X, train_y)

/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py:528: FitFailedWarning:
200 fits failed out of a total of 375.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.12/dist-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py", line 1193, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py", line 63, in _check_solver
    raise ValueError(
ValueError: Solver newton-cg supports only 'l2' or None penalties, got l1 penalty.

--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.12/dist-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py", line 1193, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py", line 63, in _check_solver
    raise ValueError(
ValueError: Solver lbfgs supports only 'l2' or None penalties, got l1 penalty.

--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.12/dist-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py", line 1193, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py", line 63, in _check_solver
    raise ValueError(
ValueError: Solver sag supports only 'l2' or None penalties, got l1 penalty.

--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.12/dist-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py", line 1193, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py", line 63, in _check_solver
    raise ValueError(
ValueError: Solver newton-cg supports only 'l2' or None penalties, got elasticnet penalty.

--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.12/dist-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py", line 1193, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py", line 63, in _check_solver
    raise ValueError(
ValueError: Solver lbfgs supports only 'l2' or None penalties, got elasticnet penalty.

--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.12/dist-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py", line 1193, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py", line 71, in _check_solver
    raise ValueError(
ValueError: Only 'saga' solver supports elasticnet penalty, got solver=liblinear.

--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.12/dist-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py", line 1193, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py", line 63, in _check_solver
    raise ValueError(
ValueError: Solver sag supports only 'l2' or None penalties, got elasticnet penalty.

--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.12/dist-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py", line 1203, in fit
    raise ValueError("l1_ratio must be specified when penalty is elasticnet.")
ValueError: l1_ratio must be specified when penalty is elasticnet.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_search.py:1108: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.92285714        nan 0.92285714 0.92285714
 0.92285714 0.92285714 0.92285714 0.92285714        nan        nan
        nan        nan        nan        nan        nan 0.92428571
        nan 0.92428571 0.92285714 0.92285714 0.92285714 0.92285714
 0.92285714        nan        nan        nan        nan        nan
        nan        nan 0.92428571        nan 0.92428571 0.92428571
 0.92428571 0.92428571 0.92428571 0.92428571        nan        nan
        nan        nan        nan        nan        nan 0.92857143
        nan 0.92714286 0.92571429 0.92571429 0.92428571 0.92571429
 0.92571429        nan        nan        nan        nan        nan
        nan        nan 0.92428571        nan 0.92142857 0.92285714
 0.92285714 0.92285714 0.92285714 0.92285714        nan        nan
        nan        nan        nan]
  warnings.warn(

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [65]:
grid.best_params_

{'C': 0.1, 'penalty': 'l1', 'solver': 'liblinear'}

In [66]:
grid.best_score_

np.float64(0.9285714285714286)

In [68]:
y_pred = grid.predict(test_X)

In [69]:
print(accuracy_score(test_y, y_pred))

0.9666666666666667

In [71]:
print(confusion_matrix(test_y, y_pred))

[[134   5]
 [  5 156]]

In [73]:
print(classification_report(test_y, y_pred))

              precision    recall  f1-score   support

           0       0.96      0.96      0.96       139
           1       0.97      0.97      0.97       161

    accuracy                           0.97       300
   macro avg       0.97      0.97      0.97       300
weighted avg       0.97      0.97      0.97       300

# **Hyperparameter with Randomized Search**

In [74]:
from sklearn.model_selection import RandomizedSearchCV

In [76]:
model = LogisticRegression()
randomcv = RandomizedSearchCV(estimator = model, param_distributions=params, cv=5, scoring='accuracy')

In [77]:
randomcv.fit(train_X, train_y)

/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py:528: FitFailedWarning:
30 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.12/dist-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py", line 1203, in fit
    raise ValueError("l1_ratio must be specified when penalty is elasticnet.")
ValueError: l1_ratio must be specified when penalty is elasticnet.

--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.12/dist-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py", line 1193, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py", line 63, in _check_solver
    raise ValueError(
ValueError: Solver sag supports only 'l2' or None penalties, got elasticnet penalty.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.12/dist-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py", line 1193, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py", line 63, in _check_solver
    raise ValueError(
ValueError: Solver newton-cg supports only 'l2' or None penalties, got elasticnet penalty.

--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.12/dist-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py", line 1193, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py", line 63, in _check_solver
    raise ValueError(
ValueError: Solver lbfgs supports only 'l2' or None penalties, got elasticnet penalty.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_search.py:1108: UserWarning: One or more of the test scores are non-finite: [0.92571429        nan        nan        nan 0.92571429        nan
 0.92428571 0.92285714        nan        nan]
  warnings.warn(

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [100, 10, 1.0, 0.1, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['newton-cg', 'lbfgs',
                                                   'liblinear', 'sag',
                                                   'saga']},
                   scoring='accuracy')

In [78]:
randomcv.best_params_

{'solver': 'newton-cg', 'penalty': 'l2', 'C': 0.1}

In [79]:
randomcv.best_score_

np.float64(0.9257142857142856)

In [82]:
y_pred = randomcv.predict(test_X)

In [84]:
print(accuracy_score(test_y, y_pred))
print('--------------------------------------')
print(confusion_matrix(test_y, y_pred))
print('--------------------------------------')
print(classification_report(test_y, y_pred))

0.9666666666666667
--------------------------------------
[[134   5]
 [  5 156]]
--------------------------------------
              precision    recall  f1-score   support

           0       0.96      0.96      0.96       139
           1       0.97      0.97      0.97       161

    accuracy                           0.97       300
   macro avg       0.97      0.97      0.97       300
weighted avg       0.97      0.97      0.97       300